# alertmanager-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: slack-notifications
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
    receivers:
      - name: slack-notifications
        slack_configs:
          - channel: '#a2-alerts'   # Change to your Slack channel
            send_resolved: true
            text: "{{ .CommonAnnotations.summary }}"
            api_url: "https://hooks.slack.com/services/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"