apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-app-alerts
  namespace: monitoring
spec:
  groups:
  - name: flask-app.rules
    rules:
    - alert: FlaskPodCrashLoop
      expr: kube_pod_container_status_restarts_total{pod=~"flask-app.*"} > 3
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Flask pod is restarting frequently"
        description: "The Flask pod has restarted more than 3 times in the last 5 minutes."
