apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-failing-probe
  namespace: monitoring
spec:
  groups:
  - name: pod-failing
    rules:
    - alert: PodCrashLooping
      expr: kube_pod_container_status_restarts_total > 3
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} is restarting frequently"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 3 times in the last 2 minutes."