apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
spec:
  groups:
  - name: test-alert-group
    rules:
    - alert: TestAlert
      expr: vector(1)   # always fires
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Test alert"
        description: "This is a test alert to verify Slack notifications."